### ISSUE TITLE
Compatible with Angular-UI

### ISSUE THREAD

**Issue by benoror** [networknt/angular-schema-form-strapselect#4]
Hi! I'm using Angular-UI in my project: In the README you mention that it supports **uiselect**, but I don't see it anywhere. How does it works? Thanks!

**Comment by benoror** [comment]
I see that UI-Select has a **refresh attribute** that does exactly the same, am I right? (Should we close the issue?)

**Comment by stevehu** [comment]
Yes. I am working to create demo apps for both strapeselect and uiselect
and connect to my demo server to get the dropdown values through cors. Stay
tuned. Thank.

**Comment by benoror** [comment]
But as I mentioned [ui-select already has dynamic async loading](https://github.com/angular-ui/ui-select/wiki/ui-select#examples-async), and there's already an [angular-schema-form's wrapper for it](https://github.com/networknt/angular-schema-form-ui-select)

Would that be enough?

**Comment by stevehu** [comment]
The first link is not schema form and the second is my repo and I am still
working on it.

**Comment by benoror** [comment]
Wow, didn't notice you were the same maintainer, sorry for that!

Kudos and keep the great work Steve!
